mesh_modifiers:
  - name: ROISelectionMeshModifier
    max_cluster_size: 1000000000
    min_cluster_size: 30
    cluster_tolerance: 0.05
    plane_distance_threshold: 0.1
tool_path_planner:
  name: PlaneSlicerRasterPlanner
  direction_generator:
    name: FixedDirectionGenerator
    x: 1
    y: 0
    z: 0
  origin_generator:
    name: FixedOriginGenerator
    x: 0
    y: 0
    z: 0
  line_spacing: 0.02
  point_spacing: 0.01
  min_hole_size: 0.1
  search_radius: 0.03
  min_segment_size: 0.05
tool_path_modifiers:
  - name: MovingAverageOrientationSmoothingModifier
    window_size: 5
  - name: SnakeOrganizationModifier
